import type { Metadata } from "next";
import { Crimson_Pro, Geist, Geist_Mono, Pacifico } from "next/font/google";
import "./globals.css";
import "yet-another-react-lightbox/styles.css";
import "yet-another-react-lightbox/plugins/thumbnails.css";
import { RegionProvider } from "@/providers/region";
import { CartProvider } from "@/providers/cart";
import CartDrawer from "@/components/cart/CartDrawer";
import { CustomerProvider } from "@/providers/customer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const crimsonPro = Crimson_Pro({
  variable: "--font-crimson-pro",
  subsets: ["latin"],
  // omit weight to include the full variable range, or use weight: "variable"
  weight: "variable",
  display: "swap",
});

const pacifico = Pacifico({
  variable: "--font-pacifico",
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${crimsonPro.variable} ${geistMono.variable} ${pacifico.variable} font-serif antialiased text-normal leading-normal`}
      >
        <RegionProvider>
          <CustomerProvider>
            <CartProvider>
              {children}
              <CartDrawer />
            </CartProvider>
          </CustomerProvider>
        </RegionProvider>
      </body>
    </html>
  );
}
